p4-16/spec/P4-16-draft-spec.mdk
=> removes priorities from table entries.

p4-16/spec/P4-16-draft-spec.mdk
Removed casts involving structs/headers.
=> Addressed issue #177

p4-16/spec/P4-16-draft-spec.mdk, p4-16/spec/grammar.mdk
This is based on the text from #139.
=> Header unions

p4-16/spec/P4-16-draft-spec.mdk
Removing OverwritingHeader.
There seems to be no text describing this behavior, only pseudo-code.
=> Addressed issue #185

p4-16/spec/P4-16-draft-spec.mdk
I am trying to close issue #76. Hopefully this summary (copied from the issue discussion) is enough to settle this issue.
=> Addressed issue #76

p4-16/spec/P4-16-draft-spec.mdk
Polishing through first section.
I'm sorry for the slightly difficult-to-review PR. I accidentally re-filled the text in Emacs and was unable to recover the old state.
=> First round of polishing

p4-16/spec/P4-16-draft-spec.mdk
* Streamlining and polishing of the prose.
* Eliminated discussion of "fixed-function" externs. That the common case, but they may be programmable (just not in P4) so it seems misleading.
=> Second round of polishing

p4-16/spec/P4-16-draft-spec.mdk
Partway through expressions. Mostly trivial changes just streamlining and making the prose internally consistent.
=> Fourth round of polishing

p4-16/spec/P4-16-draft-spec.mdk
=> Make claims about complexity truthier

p4-16/spec/P4-16-draft-spec.mdk
Addresses trivial issue in #226
=> Add forward pointers in Justification section

p4-16/spec/Makefile, p4-16/spec/P4-16-draft-spec.mdk, p4-16/spec/README.md
[DO NOT MERGE]
This experimental pull request uses the same look and feel as the P4_14 spec.
It requires:
* Xelatex
* Fonts mentioned in the README
Let's not merge in case it breaks the build for others. But if you are curious, feel free to try it out.
=> Format like P4-14 document

p4-16/spec/grammar.mdk
These are addressing additional issues from #286,
=> bug-fixes in grammar

p4-16/spec/grammar.mdk
Fixes #289 and addresses one of the requests in #286
=> fixes inconsistency for optAnnotations in table entries

p4-16/psa/p4.json
Travis is failing because docker doesn't see the entire tree.
=> copy p4.json instead of linking so that docker can build docs

p4-16/psa/PSA.mdk
=> removes ambiguity on user defined metadata types

p4-16/spec/P4-16-spec.mdk
Addresses mistakes noted in #340
=> Fixes for Example Architecture

p4-16/psa/PSA.mdk
=> specifies the returned values for uninitialized meters and registers

p4-16/psa/Makefile, p4-16/psa/examples/psa-example-clone-to-port.p4, p4-16/psa/examples/psa-example-mirror-on-drop.p4, p4-16/psa/psa.p4
Will add more clone examples. Feel free to comment.
=> add an example for clone extern

p4-16/psa/psa-profiles.mdk
@jafingerhut I added the text as a file in the directory and listed PSA profiles as something that we might want to continue to discuss.
=> adds PSA profiles as a separate file

p4-16/psa/PSA.mdk, p4-16/psa/psa.p4
And cleans up the formatting so that we minimize the number of
warnings and errors.
=> adds open issues section

p4-16/psa/PSA.mdk
In most comments, Github issues have been created to replace them, but
some are simply deleted since no one has raised any concerns about
them.  See my own comments below if you are curious whether a Github issue has been created to replace the removed TBD, or if not, why not.
=> PSA Remove most TBDs in document

p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-digest.p4
fix for #530 item 2 and formatting issue.
=> need type parameter on digest extern

p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-bridged-metadata.p4, p4-16/psa/examples/psa-example-clone-to-port.p4, p4-16/psa/examples/psa-example-counters.p4, p4-16/psa/examples/psa-example-mirror-on-drop.p4, p4-16/psa/examples/psa-example-recirculate.p4, p4-16/psa/examples/psa-example-resubmit.p4, p4-16/psa/psa.p4
Follows the agreement in the discussion on Dec 6, 2017.
=> prefix constants with PSA_

p4-16/psa/PSA.mdk
=> adds reference to P4runtime for action selector failover

p4-16/psa/psa.p4
=> adds constructor with initial register value.

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
=> raise precedence of bitwise operators

p4-16/psa/PSA.mdk
This PR sets the version for the PSA to v1.0.
=> PSA Version 1.0

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
This does not change the semantics of anything, but makes it easier to reject some illegal programs.
This is how the implementation looks as well.
=> Synchronize with implementation

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
TYPE and ENTRIES where missing
=> Updated the list of tokens that can be nonTypeName s

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
The fix proposed for issue#1336 of p4c
@mbudiu-vmw
=> Changed the place where TYPE token can be a name, to avoid conflicts

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
This should have been there with the PR describing functions.
=> Return values for functions

p4-16/psa/Makefile, p4-16/psa/examples/psa-example-parser-error-handling.p4, p4-16/psa/examples/psa-example-parser-error-handling2.p4
Also add comments to existing example program
psa-example-parser-error-handling.p4 explaining why it will not work
with P4Runtime v1.0.
=> Add variant of PSA example program that should work with P4Runtime v1.0

p4-16/spec/P4-16-spec.mdk
Also correct the cross-reference that was to section
=> P4_16: Clarify the operations supported on values of type varbit

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
There is a corresponding PR in the compiler: https://github.com/p4lang/p4c/pull/1618
=> int type: Fix for issue #331

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
The grammar has not been tested.
=> Describe structure initializer expressions

p4-16/spec/P4-16-spec.mdk
* Fix small typos found by @mkeda 
* Update Madoko metadata for v1.2.0-rc
=> v1.2.0 release candidate

p4-16/spec/README.md
Trivial edit to trigger gh-pages rebuild
=> Rebuild gh-pages

p4-16/spec/P4-16-spec.mdk
The release candidate has been out for a week now with no changes suggested. So I think we should officially release v1.2.0.
=> Update version to 1.2.0 for release

p4-16/spec/P4-16-spec.mdk
=> Eliminate small typo in Introduction

p4-16/spec/P4-16-spec.mdk
=> Forbid shifts with unknown widths

p4-16/spec/P4-16-spec.mdk
* Remove "-rc" tag
* Polish v1.2.1 ChangeLog
* Mention #834 in v1.2.1 ChangeLog
=> Final changes for v1.2.1

p4-16/spec/setup-for-ubuntu-linux.sh
It has now been successfully tested to work on Ubuntu 20.04 Linux,
too.
=> Small updates to bash script for installing Madoko on Ubuntu Linux

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
=> Support for generic structs

p4-16/spec/P4-16-spec.mdk
=> Allow casts between int and bool

p4-16/spec/P4-16-spec.mdk
Problem found during P4 LDWG meeting.
=> Fix description of valid range for header stack index.

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
See https://github.com/p4lang/p4c/pull/2518 and https://github.com/p4lang/p4c/pull/2514
=> Allow tuples with a single element

p4-16/spec/P4-16-spec.mdk
=> 0-width bitstrings

p4-16/spec/P4-16-spec.mdk
=> Clarify rules for extern functions (#972)

p4-16/spec/P4-16-spec.mdk
Fixes https://github.com/p4lang/p4-spec/issues/937
=> Extend minSizeInBits to cover more cases

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
see https://github.com/p4lang/p4c/pull/3035 and https://github.com/p4lang/p4c/pull/2905
=> Allow empty entries lists for tables

p4-16/spec/P4-16-spec.mdk
- We added the derived types that allow casting.
Fixes #961
=> Fix casting wording for Issue 961

LICENSE
containing the Apache 2.0 license.
=> Add top level file LICENSE copied from p4lang/p4c/LICENSE

p4-16/spec/P4-16-spec.mdk
See https://github.com/p4lang/p4-spec/issues/868
=> Update parser value set types

p4-16/spec/P4-16-spec.mdk
=> ?: can be a compile-time constant

p4-16/spec/P4-16-spec.mdk
=> value_set is a reserved keyword

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
=> Allow don't cares for named arguments

p4-16/spec/P4-16-spec.mdk
=> isValid is a valid header field name

p4-16/spec/P4-16-spec.mdk
=> Explain overload resolution and type inference for constructors

p4-16/spec/P4-16-spec.mdk
=> Conditionals are allowed in parsers

p4-16/spec/P4-16-spec.mdk
https://github.com/p4lang/p4-spec/pull/1082#discussion_r871606055
=> fixed a small bug in the P4₁₆ spec. that Mihai noticed recently

p4-16/spec/P4-16-spec.mdk
=> Add section with operations on match_kind values

p4-16/spec/P4-16-spec.mdk
=> Specify result type for size* methods

p4-16/spec/P4-16-spec.mdk
=> Replace 'infinite' with 'arbitrary'

p4-16/spec/P4-16-spec.mdk
=> Clarify direct type invocation

p4-16/spec/P4-16-spec.mdk
Intended to resolve this issue https://github.com/p4lang/p4-spec/issues/1120
=> Specify tables with empty key list to be the same as those with no key

p4-16/spec/P4-16-spec.mdk
=> const default default_action

p4-16/spec/P4-16-spec.mdk
Fixes #1123
Compiler changes: https://github.com/p4lang/p4c/pull/3196
=> static_assert definition

p4-16/spec/P4-16-spec.mdk
=> Clarify inout parameters semantics

p4-16/spec/P4-16-spec.mdk
=> Fix wrong clarification

p4-16/spec/P4-16-spec.mdk
=> Clarified semantics of lookahed on headers

p4-16/spec/P4-16-spec.mdk
=> Explicitly disallow overloading parsers, controls, packages

p4-16/spec/P4-16-spec.mdk
=> Add changelog for merged feature

p4-16/psa/PSA.mdk
This brings it closer to the P4_16 and PNA specifications.
=> Add definition of P4Example Madoko 'macro' to PSA spec, and use it

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
Fixes #1044 
To be discussed by the LDWG.
=> Narrow the legal types that can be introduced by `type`

p4-16/spec/P4-16-spec.mdk
=> Add 'string' as a reserved keyword

p4-16/spec/grammar.mdk
This makes it easier to compare the two grammars using simple tools like diff.
=> Make grammar.mdk file more similar to p4c's grammar

README.md
=> Add link to archived discussions in README

README.md
=> Fix incorrect URL to old meeting notes

p4-16/spec/P4-16-spec.mdk
=> Clarify constraints on parameters with default values

p4-16/spec/P4-16-spec.mdk
This PR adds the distinctness of fields for types such as enum, error, struct, header, and header union.
=> Add distinct fields

p4-16/spec/P4-16-spec.mdk
=> Add section on operations on extern objects

p4-16/spec/P4-16-spec.mdk
=> Added header stack expressions

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
In particular, to match the changes made to the p4c implementation with this commit:
https://github.com/p4lang/p4c/commit/64683c958b64b15a5a20c04c5c793a25b6fdb748
=> Update spec grammar to more closely match open source p4c implementation

README.md, p4-16/spec/P4-16-spec.mdk
Also updated changelog and added a new section for the next release.
=> Release v1.2.5

p4-16/spec/P4-16-spec.adoc
Minor fixes for text introduced in #1315.
=> Fix format, remove remrant of conflict resolution
