p4-16/spec/P4-16-draft-spec.mdk
Clarify the behavior of invoking the same type multiple times within the same scope.
=> Further clarification of direct type invocation.

p4-16/spec/P4-16-draft-spec.mdk
* Allow `default_action` to be omitted.
* Clarify that a table-miss on a table without a default action behaves like a no-op.
* Remove some trailing whitespace.
=> Clarify semantics of default_action

p4-16/spec/P4-16-draft-spec.mdk
First attempt to capture the restriction on top-level instances discussed in previous LDWG meeting and by email on 5/9.
Specifically, we restrict instantiations to a single top-level package, along with the parsers/controls mandated by the architecture. 
Added a short example to illustrate.
Note that declaration constants remain -- they are harmless.
=> Add text restricting top-level instantiations

p4-16/spec/P4-16-draft-spec.mdk
Although it touches almost every line, there are no material changes in this commit. 
Some lines are still longer than 80 columns when adding breaks would  cause a Madoko code block \`\`\` ... \`\`\` to appear at the start of a line. I also had to tweak the phrasing of a small number of paragraphs which began with a code block for the same reason.
=> Reformat Madoko sources to fit in 80 columns

p4-16/spec/P4-16-draft-spec.mdk
Do not merge until after #201.
Add labels to subsections of control-plane names that were causing
conflicts with `sec-tables` and `sec-actions` labels elsewhere. Also
added labels to other subsections (e.g. `sec-cp-keys`) to avoid the
possibility of the same error in the future.
Fixes #199
=> Fix section label clashes

p4-16/spec/P4-16-draft-spec.mdk
Apparently having this text on the same line was causing some warnings
in the LaTeX output about undefined references.
=> Avoid LaTeX warnings of undefined cross-refs

p4-16/spec/P4-16-draft-spec.mdk
I think this fixes all occurrences of this particular kind of incorrect Madoko markup, which was causing the { #cross-ref-label } to appear in the PDF output.
=> Fix a couple more instances of incorrect Madoko markup

p4-16/spec/P4-16-draft-spec.mdk, p4-16/spec/p4.json
**Spacing**
This pull request fixes some spacing (missing space between two sentences), changes references to 'run time' and 'run-time' to 'runtime' (even though I prefer the former) to be consistent with the common usage in the document.
**Capitalization**
Changed Header Union references to Header union to make it consistent with Header type and Header stack. Lower-cased Boolean to be consistent with uses of integer.  Changed one instance of Compile-Time to Compile-time to match the other reference.
**Formatting**
Fixed some formatting issues where comma grouped items were surrounded by \`\`\`, when I noticed it (e.g. \`\`\`in, inout\`\`\` and \`\`\`out\`\`\` becomes: \`\`\`in\`\`\`, \`\`\`inout\`\`\`, and \`\`\`out\`\`\` (with the added oxford comma).  Added '\#undef' and '\#line' to …
=> Some spacing, capitalization, formatting, and oxford comma fixes

p4-16/spec/P4-16-draft-spec.mdk, p4-16/spec/p4.json
Also to the list of typeKeywords in p4.json, which controls how color
highlighting is done in P4 code samples.
=> Add header_union to list of derived types that create scopes

p4-16/spec/P4-16-draft-spec.mdk
Also eliminate an unmatched right paren, and break up long text inside
``` into many shorter texts, because the long one Madoko forces to be
kept on one long line that doesn't fit in page width.
=> Mention header unions in 2 more places they ought to be

p4-16/spec/P4-16-draft-spec.mdk
Only the first part of this change actually fixes badness in the PDF
output.  The others do not make any visual change in the output, but
they do eliminate the last of the occurrences of ``` as the first
non-whitespace on a line, except for the definitions of P4Example,
etc.
=> Another Madoko markup fix

p4-16/spec/P4-16-draft-spec.mdk
I happened to notice that whenever Madoko has warnings like this early
in its output:
warning: unable to read language definition: parsed_packet
warning: unable to read language definition: table
warning: unable to read language definition: control
warning: unable to read language definition: parser
those occur because it found ```parsed_packet``` at the beginning of a
line somewhere in the input .mdk file.
=> More Madoko markup fixes

p4-16/spec/P4-16-draft-spec.mdk
I find the mention of ISO/IEC 2382 somewhat odd. It sets up expectations for a highly pedantic document, which this specification is not.
How do people feel about deleting it and replacing it with a more
direct statement that captures what we are trying to convey?
=> reduce formality

p4-16/spec/P4-16-draft-spec.mdk
Motivation for the proposed change in semantics for header unions
Example P4 program fragment:
```
header_union u_t {
h1_t h1;
h2_t h2;
h3_t h3;
h4_t h4;
}
u_t u;
```
If you have a header_union variable u that is in one of many possible
states (e.g. perhaps member h1 is valid, or h2 is valid, or no members
are valid) and you wish to guarantee that all members of u become
invalid, the only way to write that given the current semantics is to
cause each member header to become invalidated, either with
setInvalid() or assignment from an invalid header of the appropriate
type.  Here is an example of the first way:
```
u.h1.setInvalid();
u.h2.setInvalid();
u.h3.setInvalid();
u.h4.setInvalid();
```
Moreover, this assignment:
```
u.h1 = h1_variable;
```
has the surprising behavior of being a …
=> Simplify semantics of header union member setInvalidate() and assignment

p4-16/spec/P4-16-draft-spec.mdk
* Fix typo in TCP options parsing example (missing cast to `bit<32>`).
* Add back-pointer to section on header unions, which gives the full definitions of all auxiliary types, in example showing a use of `lookahead` for TCP options parsing.
=> Small fixes to TCP options examples

p4-16/spec/P4-16-draft-spec.mdk
* Fix names to abide by our metavariable conventions (uppercase for controls, etc.)
*  Tweak examples to avoid causing confusion due to restrictions on top-level instantiation.
* Fixed a typo "simple" -> "Simple"
=> Small fixes to naming for instances

p4-16/spec/P4-16-draft-spec.mdk
* Typeset P4Examples in light yellow
* Change `code` to a 10pt font to avoid running into the margin in HTML.
* Fix table of types
* Break some long lines to avoid "Overfull hbox..." warnings in TeX.
* Spell checking
=> Final formatting fixes

p4-16/spec/P4-16-spec.mdk
Fixing a few non-unicode characters in the spec that are caught by the python-markdown library.
=> fix non-unicode characters

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
Because we don't require a default_action, and the compiler will (logically) insert a NoAction call in this case, it makes sense to allow tables to have an empty actions list.
=> Allow empty actions list

p4-16/psa/Makefile, p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-counters.p4, p4-16/psa/psa.p4
With this initial psa.p4 file, the resulting PSA document is the same
before and after this change.
This psa.p4 is not identical to the one in the p4lang/p4c repository.  That one has extra comments, and this one has some small fixes made to it in the p4-spec repository in the last couple of weeks.
This psa.p4 does compile when #include'd into a P4_16 program, without errors.
=> Use Madoko file fragments to include code from separate psa.p4 file

p4-16/psa/PSA.mdk
=> address the semantics of truncate

p4-16/psa/PSA.mdk, p4-16/psa/psa.p4
This change also includes a proposed change of naming things "direct counters" and "indexed counters" (the latter name "indexed" in place of what has previously been called "indirect").  It isn't a big deal, and I can back out that part to go back to indirect if that is what people want.  I just wanted to propose the name "indexed", since it doesn't have any connotations of adding a level of indirection that the name "indirect" can.
=> Some additions to description of meters.

p4-16/psa/PSA.mdk
It is up to about 24 pages now, and a TOC can be nice for jumping to selected sections.
=> Add table of contents to PSA spec

p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-counters.p4, p4-16/psa/psa.p4
@hanw @vgurevich Would be great if you can read this over and see if anything looks like it needs further changes.  As usual, I am not considering any of this 'final' -- just more things specified in more detail than it was in the original PSA draft document,  and in this case replacing PRE/BQE methods with metadata and helper actions.
=> Replace most PRE/BQE methods calls with actions on metadata

p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-counters.p4, p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/psa.p4
Adds a section on naming conventions and follows up on implementing it.
Fixes #315.
=> cleanup: naming conventions, grammar, text, etc.

p4-16/psa/psa.p4
The `emit` method for the `recirculate` extern was missing the declaration of type parameter `T`.
=> Fix typo in PSA

p4-16/psa/PSA.mdk, p4-16/psa/psa.p4
The text briefly mentions how a user's P4 program can use this to
generate pseudo-random values with non-uniform distributions.
=> Simplify the Random extern for uniform distributions only

p4-16/psa/examples/psa-example-counters.p4, p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/examples/psa-example-register2.p4, p4-16/psa/examples/psa-example-value-sets.p4, p4-16/psa/examples/psa-example-value-sets2.p4, p4-16/psa/examples/psa-example-value-sets3.p4, p4-16/psa/psa.p4
We want these structs to have fields with defined values when the
Ingress and Egress control blocks begin execution.  This cannot be
done if they are defined as direction 'out', but can if they are
defined as direction 'inout'.
Also adds a missing type parameter <T> to one emit method definition
in psa.p4 that caused compilation errors.
=> Change direction of some Ingress and Egress parameters from out to inout

p4-16/psa/psa.p4
I am feeling itchy about having to write down `PacketReplicationEngine pre` every time I create an ingress block. I hope we can move them to the top level package definition, where they belong. Ideally, users shouldn't even need to create an instance of PRE, but I haven't figured out how to do that.
=> move PRE and BQE declaration from ingress/egress to top level package

p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-incremental-checksum.p4, p4-16/psa/examples/psa-example-incremental-checksum2.p4, p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/psa.p4
Discussed at 2017-Nov-01 PSA working group meeting.
Keep clear and get methods as is.
Rename update to add.  Rename remove to subtract.
Add get_state method for returning the internal checksum state from an
InternetChecksum instance in one parser or control, and set_state
method for causing an instance to go to that same state.  Useful for
some kinds of incremental checksum computation performed across
different parsers or control blocks.
=> PSA: Updates to InternetChecksum extern

p4-16/psa/examples/psa-example-clone-to-port.p4, p4-16/psa/examples/psa-example-incremental-checksum.p4, p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/examples/psa-example-register2.p4, p4-16/psa/examples/psa-example-value-sets.p4, p4-16/psa/examples/psa-example-value-sets2.p4, p4-16/psa/examples/psa-example-value-sets3.p4
Nothing deep here -- just the same kind of changes made yesterday to update one of the examples for the new psa.p4 control and package definitions.  They all compile cleanly with the latest p4test again (modulo a few warnings about ostd not being completely initialized, which is normal).
=> PSA - Update examples for latest psa.p4 file

p4-16/psa/PSA.mdk, p4-16/psa/psa.p4
Nothing should be deleted or added here, simply put in a different order.
Two small exceptions to that:
I deleted an old definition of Deparser in psa.p4, since it has been replaced with separate IngressDeparser and EgressDeparser controls.
I added the field 'instance' that was missing in the fields received by the egress parser in the 'initial metadata values received by egress' table.
=> PSA - attempt to put sections in a better order

p4-16/spec/P4-16-spec.mdk
This PR re-applies the changes that were submitted as part of #381 and which need to wait for the language working group discussion.
=> [do not merge] restores PR #381: Proposed additions to P4_16 spec: restrictions on use of stateful objects

p4-16/psa/PSA.mdk
- consistent use of P4 Runtime API
- consistent use of Ingress/Egress
- remove TBD on packet_in.lenght() and support the same semantics as P4_16.
- removed references to Antonin for finalizing the P4 Runtime format
of class of service methods
- clone and resubmit: moved the add_metadata discussion to the open
issues, since it is not defined in the extern.
- add recirculate extern definition
- removed reference to making the PRE/BQE available to the Ingress/Egress
controls
=> editorial changes

p4-16/psa/psa.p4
Without this change, a recent version of p4test gives an error while
attempting to compile this code.
=> PSA Fix syntax error psa.p4

p4-16/psa/PSA.mdk
@jafingerhut I was searching for TBDs and I realized that we had a preformatted paragraph for them -- turns them red so we can find them easily. This PR simply uses the the paragraph to mark them. I would like to see whether we can resolve any of these with some light discussion. There are a few that I should like to think are not controversial!
=> use preformatted TBDs

p4-16/psa/Makefile, p4-16/psa/examples/psa-example-incremental-checksum.p4, p4-16/psa/examples/psa-example-incremental-checksum2.p4, p4-16/psa/examples/psa-example-mirror-on-drop.p4, p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/examples/psa-example-register1.p4, p4-16/psa/examples/psa-example-register2.p4, p4-16/psa/examples/psa-example-value-sets.p4, p4-16/psa/examples/psa-example-value-sets2.p4, p4-16/psa/examples/psa-example-value-sets3.p4
Nothing fancy here -- just updating the other PSA example programs for the most recent changes in psa.p4.  Only one or two of them were updated when psa.p4 was last changed, to test those changes at least a little bit, but waiting for the changes to settle a bit before 'catching up' to the latest version with the rest of the examples.
=> Update PSA example programs for latest version of psa.p4

p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-clone-to-port.p4, p4-16/psa/psa.p4
Some text in the clone section describes what the control plane must
configure for each clone session.
=> PSA Update clone operations to use clone_session_id

p4-16/psa/PSA.mdk, p4-16/psa/psa.p4
Also restrictions on what kinds of items can be added to multicast
groups.
=> Add a section with notes on PRE multicast replication behavior

p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-recirculate.p4, p4-16/psa/psa.p4
One attempt to do recirculate in PSA and updated some text.
So far, it seems the `recirculate` flag is still necessary to inform the egress deparser that the ingress pipeline has made a decision to recirculate a packet by setting the `egress_port` to `PORT_RECIRCULATE`. The egress deparser needs to know if a packet is recirculation packet by either checking the `egress_port == PORT_RECIRCULATE` or checking `recirculate_flag == 1`. The issue with `egress_port` is that it is not in the `psa_egress_output_metadata_t`, and therefore not visible in egress deparser. On the other hand, the `recirculate` flag is visible in egress deparser. But the caveat is that the `recirculate` flag should be read-only and should be set by the environment. However, `recirculate` flag is currently in …
=> add an example to do recirculate in PSA

p4-16/psa/Makefile, p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-bridged-metadata.p4, p4-16/psa/examples/psa-example-clone-to-port.p4, p4-16/psa/examples/psa-example-counters.p4, p4-16/psa/examples/psa-example-digest.p4, p4-16/psa/examples/psa-example-incremental-checksum.p4, p4-16/psa/examples/psa-example-incremental-checksum2.p4, p4-16/psa/examples/psa-example-mirror-on-drop.p4, p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/examples/psa-example-recirculate.p4, p4-16/psa/examples/psa-example-register1.p4, p4-16/psa/examples/psa-example-register2.p4, p4-16/psa/examples/psa-example-resubmit.p4, p4-16/psa/examples/psa-example-value-sets.p4, p4-16/psa/examples/psa-example-value-sets2.p4, p4-16/psa/examples/psa-example-value-sets3.p4, p4-16/psa/psa.p4
Changes include:
+ Eliminate recirculate and resubmit extern objects from psa.p4.
+ Proposed addition of a new struct that contains only egress_port field, to be given as 'in' parameter to the egress deparser, so it can distinguish between recirculated packets vs. others.  It something like this to implement psa_recirculate() function correctly.  This is one of several ways to do it, but we could choose something else.
+ Many small changes to PSA.mdk mentioning things about recirculate, and updating them to the current planned way to do it.
+ A few other small corrections and occurrences of rewording that I hope are improvements in PSA.mdk.
=> Many edits to clean up move of recirculate decision to ingress

p4-16/psa/Makefile, p4-16/psa/PSA.mdk, p4-16/psa/examples/psa-example-bridged-metadata.p4, p4-16/psa/examples/psa-example-clone-to-port.p4, p4-16/psa/examples/psa-example-counters.p4, p4-16/psa/examples/psa-example-digest.p4, p4-16/psa/examples/psa-example-incremental-checksum.p4, p4-16/psa/examples/psa-example-incremental-checksum2.p4, p4-16/psa/examples/psa-example-mirror-on-drop.p4, p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/examples/psa-example-recirculate.p4, p4-16/psa/examples/psa-example-register1.p4, p4-16/psa/examples/psa-example-register2.p4, p4-16/psa/examples/psa-example-resubmit.p4, p4-16/psa/examples/psa-example-value-sets.p4, p4-16/psa/examples/psa-example-value-sets2.p4, p4-16/psa/examples/psa-example-value-sets3.p4, p4-16/psa/psa.p4
The only reason it was there was to carry the parser error out of the
ingress and egress parsers, but the PSA architecture can just
transport those parser errors to the ingress and egress control blocks
'somehow' by however the architecture does it, without making it an
'out' parameter of the parsers.
Note that the example architecture in the P4_16 language specification
does the same thing.
=> Remove unnecessary psa_parser_output_metadata_t struct

p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/examples/psa-example-parser-error-handling.p4, p4-16/psa/psa.p4
The examples compile without errors again, with these changes.
=> PSA Update psa.p4 and example programs for recent renaming

p4-14/v1.0.5/tex/p4.pt
This PR takes a first step toward the "P4_16 v1.0.0 is right" option identified by @jafingerhut.
This PR will be easier to review after #500 is merged.
=>  Harmonize P4_14 and P4_16 semantics of header stacks

p4-16/psa/examples/psa-example-parser-error-handling.p4
Madoko gives a warning message, I believe the condition in this
situation causing it is: if there are multiple files in INCLUDE
directives with the same name/id after BEGIN/END, then the warning
occurs.
The warning goes away when I delete these two lines.  PSA.mdk only
uses this name to INCLUDE a sample of code from the file
examples/psa-example-parser-checksum.p4, not
examples/psa-example-parser-error-handling.p4, so remove the
occurrence that we do not use or need.
=> PSA Remove duplicate Madoko include tags

p4-16/psa/Makefile, p4-16/psa/charter/Makefile
Apparently madoko does not deal graciously with paths in the source
name, so had to split charter building from psa building.
=> PSA: fix travis build

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
This PR introduces saturating arithmetic operators for signed and
unsigned integers of fixed width (per our discussion in the WG).
=> adds saturating addition and subtraction operators

p4-16/spec/P4-16-spec.mdk
The compiler does not implement a `@globalname` annotation. It looks like `@globalname(x)` is the same as `@name(.x)`, so I simplified the spec to remove the unnecessary annotation. This is supported by the fact that the control-plane API seems to work fine without using `@globalname`.
=> Removed globalname annotation

p4-16/psa/psa.p4
Fixed direction of InternetChecksum::set_state's argument. Also added a missing key parameter in DirectCounter's set API.
=> Fixed InternetChecksum parameter direction and a DirectCounter API typo.

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
Hey All,
Following up on the discussion in #611, this pull request attempts to capture the proposal in the P4-16 specification document.
=> Adding serializable enums (or enums with backing types and specified representations).

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
I think it is safest to allow no operations; allowing only some operations is really a hack with lots of exceptions. The right way to allow operations is to create functions that can operate on such values:
```
type bit<32> B32;
B32 mask(in B32 left, in B32 right) { return (B32)((bit<32>)left & (bit<32>)right); }
```
=> Added specification for new type

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
Unfortunately I have realized that allowing default values for controls in a package will require fresh type variables - since in this case the type of the data coming out of a parser is no longer the same as the type of data going through the control. This will be fixable if we reintroduce generic controls later.
```
struct Empty {}
control nothing(inout Empty h, inout Empty m) {
apply {}
}
parser parserProto<H, M>(packet_in p, out H h, inout M m);
control controlProto<H, M>(inout H h, inout M m);
package pack<HP, MP, HC, MC>(@optional parserProto<HP, MP> _parser,  // optional parameter
controlProto<HC, MC> _control = nothing()); // default parameter value
pack() main;   // No value for _parser, _control is an instance of nothing()
```
Ideally this would be written as follows:
```
parser …
```
=> Specification for named arguments

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
This introduces into the grammar the suggestion #635 .
In the compiler, it is already the case that suggestion #635 is implemented.
=> Allow optional type parameters to be any name, and not just nonTypeName

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
If expressionList and keyValueList can both be empty,
then the grammar is ambiguous, since an annotations with
parenthesis but no arguments inside could either correspond
to an annotation with an empty expressionList or an annnotation with
an empty keyValueList.
The change suggested by this commit matches the
actual current implementation of the P4 compiler, and follows a suggestion by @mbudiu-vmw on pr #634 about suggestion #633 .
=> Require keyValueList to be non-empty

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
+ Added into the grammar the rule for valueSetDeclaration (was missing).
+ Added to the spec text a quote of the valueSetDeclaration rule (optional).
=> Fix: add value sets to grammar

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
As pointed out by @mbudiu-vmw
everywhere else in the grammar, the quotes are single.
=> Change double quotes into single quotes for consistency.

p4-16/spec/P4-16-spec.mdk
This is a bugfix.
In the spec, in the description of newtype declarations, the grammar extract was wrong, as it did not use the correct token ( `TYPE_IDENTIFIER` was used instead of `TYPE` ).
The corresponding section in the grammar has not the same bug.
=> Corrected token involved in newtype declarations in the spec description

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
There where some parser actions left in the grammar and in a grammar extract in the spec; removed them.
=> Removed parser actions from grammar

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
This was already the case for all other toplevel paths, so this modification adds consistency.
As dotPrefix is, in the grammar, an alias of '.' , this doesn't change at all the set of syntactically correct programs.
=> Use dotPrefix non terminal for toplevel paths in expressions

p4-16/spec/P4-16-spec.mdk
As the rule for declaring functions uses the functionPrototype
rule, I find it more clear to include the definition of functionPrototype
in the same extract.
What do you think?
(This is a very small modification, just for more clarity in the spec document)
=> Extend grammar extract for function declarations in the spec

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
The return type of extern functions can be a specialized type
receiving a type variable (hence a nonTypeName) as a type argument.
For example:
`extern widget<T> createWidget<T, U>(U a, T b);`
(Example taken from `factory2.p4` in `p4-c/testdata/p4_16_samples/`)
For this reason, the non-terminal `typeArg` needs to have
`nonTypeName` as one of its variants.
But this introduces a conflict:
when the parser sees
`nonTypeName '<' nonTypeName`
it can't know if it is a `expression '<' expression` of a comparison
or a `expression '<' typeArg ...` of the begining of a function call.
This is why the non-terminal realTypeArg (corresponding to the old typeArg)
was introduced: to avoid that conflict.
This modification to the grammar corresponds to what is already implemented
by the compiler.
=> TypeArg can be nonTypeName, because of the return type of externs

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
This pr reflects into the grammar & spec
the changes made by pr1363 to p4c .
=> Allow table property names to be type names

p4-16/spec/P4-16-spec.mdk
We add an "accept" transition after invoking the sub-parser. Without it
there is an implicit "reject" transition for all packets, no matter what
state the sub-parser ends in.
I believe the example makes more sense like this and is more
representative of what someone would actually write.
=> Clarify sub-parser example in P4_16 spec

p4-16/psa/PSA.mdk
In general, if a feature is something we do not want to require PSA
implementations to support in some version of the PSA spec, it is
preferable to say "X need not be supported" rather than "you cannot do
X".  The former means a PSA implementation _may_ support it if they
want, and they should be able to.  Saying "you cannot do X" makes it
sound like an implementation will violate the PSA spec if it supports
features that are not required.
=> PSA - Change prohibition to "need not be supported"

p4-16/spec/P4-16-spec.mdk
The pdf tables were rendered wrong without these fixes.
=> Formatting fixes

p4-16/spec/P4-16-spec.mdk
This suggested change arose during discussion of this issue: https://github.com/p4lang/p4-spec/issues/715
but that issue is _not_ resolved by this PR, as it was originally about a different question not addressed here.
=> Constrain keys to be unique in key-value pair values for annotations

p4-16/psa/psa.p4
This will make the file match what we plan to have in the p4c
implementation, to make it easier to keep these files synchronized in
the future.
=> Update psa.p4 include file to have example widths for BMv2

p4-16/spec/P4-16-spec.mdk
I moved this text into its own section, and added cross-references to
it from where the text was moved from, Section 8.14 "Operations on
headers", and another in Section 8.13 "Operations on structs", even
though it really does apply to reading uninitialized of _any_ types.
Motivation for this movement: The moved text specifially describes the
behavior when an uninitialized value of type `enum` or `error` is
read, even though a header is not allowed to contain fields with those
types.  With the text in Section 8.14, one could be easily be confused
into believing that it implied that a header could contain fields of
those types.
The only changes I made to the moved text are as follows:
+ Changed the first sentence to "The result of reading a field" to
"The result of reading a value", since …
=> P4_16: Move text on reading uninit vals and writing to invalid headers

p4-16/spec/P4-16-spec.mdk
The contents of the table are based upon the current p4c
implementation, tested via the p4test command.
=> Add a table listing which types upon which you can do typedef and type

p4-16/spec/P4-16-spec.mdk
Before this change, the word "serializable" does not occur anywhere in
the language specification.  An enum value with an underlying type is
often called a serializable enum in conversation between P4
implementers, including in the p4c implementation, so having a way to
find it in the language spec by that name seems like a good idea.
=> Mention that an enum with an underlying type is also called serializable

p4-16/spec/P4-16-spec.mdk
The diff is actually quite small, but there was some extraneous spaces as well.
=> One explicit cast was omitted

p4-16/spec/P4-16-spec.mdk
This allows the type `int<1>` and adds slices for signed values.
@jafingerhut : you have claimed this issue, but I wanted to discuss this next Monday so I took over.
=> Allow `int<1>`: fix for issue #668

p4-16/spec/P4-16-spec.mdk
This is a small change to the spec that allows table.apply().miss in addition to table.apply().hit
=> Issue #761: Add support for the apply() miss field

p4-16/spec/P4-16-spec.mdk
* For consistency, rename #sec-strings to #sec-string-type
* Fix broken link to #sec-string section in description of v1.2.0
changes, by making it point to #sec-string-type
=> Update links for string type

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
This PR is motivated by a discrepancy between the language specification and `p4c` (see  p4lang/p4c#2129).
It makes two changes:
1. Modify the grammar to eliminate optional annotations on `actionRef` components `const` table entries.
2. Extend the example of `const` table entries to illustrate a use of an `actionRef` without parentheses.
=> Eliminate annotations on action bindings

p4-16/spec/P4-16-spec.mdk
This should be merged after #717
=> Added structure-valued expressions

p4-16/spec/P4-16-spec.mdk
This PR fixes a mismatch between the compiler (see p4lang/p4c#2301) and the specification. It seems to have been an oversight.
=> Add '0d' syntax for decimal literals

p4-16/spec/P4-16-spec.mdk
Note that currently default values are not used anywhere in the spec. The intention is to have an additional pull request that will specify when or how default values can be used. But I think that this part will be less controversial so I factored it out separately.
=> Introduce default values

p4-16/spec/P4-16-spec.mdk
Intended to address issue https://github.com/p4lang/p4-spec/issues/842
=> Explicitly allow implicit casts for direction 'in' arguments

p4-16/spec/P4-16-spec.mdk
Include an example demonstrating how a P4 compiler might choose to
implement a table apply call where the table key expressions have side
effects.
=> Define the order of table key evaluation explicitly

p4-16/spec/P4-16-spec.mdk
Some places this is mentioned, otherwise it is not.
Issue #885.
=> P4-16-spec: Consistently consider the 'miss' field in apply_result(T).

p4-16/spec/P4-16-spec.mdk
This small PR introduces tuple field extraction. Initially I was thinking to use a syntax like `t.0` to extract a field, but using `t.f0` seems equally good and requires no changes to the grammar, and will not introduce ambiguities.
=> Tuple fields

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
I found a few differences between the latest p4lang/p4c P4_16 grammar, as compared to the grammar.mdk file in the P4_16 spec repository, when reviewing another issue on the spec recently.
I suspect that some of these differences might be due to experimental features in p4c, but some of them look like things we might want to update in the spec's grammar.mdk file.  Happy to get comments about which differences are in which category, and update this PR.
=> Possible updates/corrections to P4_16 spec grammar

p4-16/psa/examples/psa-example-bridged-metadata.p4, p4-16/psa/examples/psa-example-clone-to-port.p4, p4-16/psa/examples/psa-example-counters.p4, p4-16/psa/examples/psa-example-digest.p4, p4-16/psa/examples/psa-example-drop-all.p4, p4-16/psa/examples/psa-example-hello-world.p4, p4-16/psa/examples/psa-example-incremental-checksum.p4, p4-16/psa/examples/psa-example-incremental-checksum2.p4, p4-16/psa/examples/psa-example-mirror-on-drop.p4, p4-16/psa/examples/psa-example-parser-checksum.p4, p4-16/psa/examples/psa-example-parser-error-handling.p4, p4-16/psa/examples/psa-example-parser-error-handling2.p4, p4-16/psa/examples/psa-example-recirculate.p4, p4-16/psa/examples/psa-example-register1.p4, p4-16/psa/examples/psa-example-register2.p4, p4-16/psa/examples/psa-example-resubmit.p4, p4-16/psa/examples/psa-for-bmv2.p4
Before this change,the p4-16/psa/psa.p4 include file contained a mix
of one section intended to be an example for a BMv2 target-specific
psa.p4 include file, and also a section with 'unspecified' for several
bit widths intended for generating the PSA specification text.
With this change, that file is only for the purpose of generating the
PSA specification.  It is no longer compilable, and contains an #error
directive that should make this obvious to anyone who tries to include
it while compiling a P4 program.  It also has comments linking to two
compilable example target-specific psa.p4 include files in the
p4lang/p4c repository.
Add a copy of the compilable version of the BMv2-specific psa.p4
include file in p4-16/psa/examples/psa-for-bmv2.p4, simply so the
example PSA programs can …
=> Make psa.p4 include file in spec repo explicitly not compilable

p4-16/spec/P4-16-spec.mdk
- We clarified that both shifts and concatenation are the exceptions among the binary operations that require two operands to have the same type.
- We added concatenation to the list of allowed binary operations for bit-strings and fixed-width integers.
- We grouped shift, bit slicing, and concatenation in 8.6 (in a similar style to 8.5) to leave them outside the restriction of two operands must have the same types; we swapped shift and bit slicing in 8.5 since shift is the only item among the three that has a different description in 8.5 and 8.6.
- We added bitwise operations explicitly to the list of operations in 8.6 to make it more readable.
- We changed the title from "Concatenation" to "A note about concatenation" for 8.6.1 to make it parallel to 8.6.2.
Fixes  #956
=> Add concatenation for Issue 956

p4-16/spec/P4-16-spec.mdk
- We added value sets to the control plane names with a new subsection following the existing format.
Fixes #962
=> Add control plane names for Issue 962

p4-16/spec/P4-16-spec.mdk
- We listed explicitly the allowed "positive and constant" right operands for shifts on arbitrary-width integers.
- We moved the subsection of "A note about shifts" to after 8.7 and added a beginning paragraph to describe the general patterns of the allowed operands for shifts.
- We modified the reason why an arithmetic operation is illegal accordingly.
Fixes #959
=> Clarify shifting int by constant bit<w> for Issue 959

p4-16/spec/P4-16-spec.mdk
- We added a reference to the implicit cast section in the enum operations section.
- We re-asserted that the implicit casts from enum to its underlying types is always safe and allowed, with extra examples.
Fixes #958
=> Clarify implicit casts of enum for Issue 958

p4-16/spec/P4-16-spec.mdk
- We exclude shifts and concatenation from implicit casts.
- We changed the shift example to emphasize that there is no implicit cast.
Fixes #957
=> Improve implicit casts for Issue 957

p4-16/psa/PSA.mdk
> a "Portable NIC Architecture" (if such a thing is developed)
This comment implies that the PNA architecture specification doesn't exist yet, however, a draft version of [PNA](https://p4.org/p4-spec/docs/PNA-v0.5.0.html) (version 0.5) has been released in May 2021.
=> psa: Update comment about PNA

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
- We removed `instantiation` from `statementOrDeclaration` in grammar
Fixes #975
=> Remove instantiation from block for Issue 975

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
See https://github.com/p4lang/p4c/pull/3099 for several P4 programs that cannot be compiled without this change.
=> match_kind is a base type

p4-16/spec/P4-16-spec.mdk
in favor of structure-valued expressions, which can do everything that
structure initializers could, and more.
=> Remove structure initializers from the spec

p4-16/spec/P4-16-spec.mdk
=> One cannot have variables with type int

p4-16/spec/P4-16-spec.mdk
Since we made switch statements more general we should allow them in actions.
By forbidding table applications we are more precise.
=> Allow switch statements in actions

p4-16/spec/P4-16-spec.mdk
- We added parser and control types to the types that allow optional parameters.
Fixes #977
=> Add types with optional parameters for Issue 977

p4-16/spec/P4-16-spec.mdk
Intended as an alternative to p4-spec PR #852.
=> Forbid applying tables within action parameters in a table definition

p4-16/spec/P4-16-spec.mdk
The changes to the code snippet comments are because in the generated
HTML version those comments extend outside of a shaded background box.
By breaking the lines as suggested, I have verified that the text lies
within that shaded background box in both PDF and HTML versions.
=> Small fixes suggested by Cristian Dumitrescu

p4-16/spec/P4-16-spec.mdk
Thanks to Cristian Dumitrescu for pointing out that this example code did not look legal.
There are multiple options for making it legal P4_16 code.  This is just one way, which I have verified passes with a recent version of p4test.
=> Correct example that uses LearningProvider extern object

p4-16/spec/P4-16-spec.mdk
I noticed string was missing from the type nesting rules
table and this adds it.
=> Add string type to "Type nesting rules" table

p4-16/spec/P4-16-spec.mdk
This clearifies a few things
* the order of the initialization does not matter
* All of the fields of the struct/header types need be initialized
These might seem implicit but when writing a specifications like this,
they should be explicit.
=> Clearify structured-value expressions and their fields

p4-16/psa/PSA.mdk
This pull request removes the word `could` in the following sentence:
```
Subsequent packets in the flow could would be mapped to the same cell;
```
=> psa: Fix typo

p4-16/spec/P4-16-spec.mdk
Fixes #1045 
Already fixed in the compiler by https://github.com/p4lang/p4c/pull/3174
=> Do not allow typedef with unspecialized generic types

p4-16/spec/P4-16-spec.mdk
=> Allow specifying structure types for list expressions

p4-16/spec/P4-16-spec.mdk
=> Specify operations on values typed as type variables

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
I could argue that this is a bug, but perhaps it should be discussed in the design working group.
=> Allow direct invocation of generic controls/parsers 

p4-16/spec/P4-16-spec.mdk
The ';' is wrong inside the enum and should be removed. Inside enums, ','
is the seperator but since there is only one value, it can be removed.
=> Fix small typo in example in sec-implicit-casts section

p4-16/spec/P4-16-spec.mdk
These two operators actually have the highest precedence
even higher than just `&` (just above the `?:` operator)
in both the grammer in the specifications and even in the reference compiler.
=> mask (`&&&`) and range (`..`) operators have the wrong precedence

p4-16/spec/P4-16-spec.mdk
=> Clarifications on range operators

p4-16/spec/P4-16-spec.mdk
In the "Operations on lists" section, the reference for tuple types points to a section that does not cover tuple types. This small change updates the reference to point to the tuple types section.
=> Fix tuple-type reference.

p4-16/spec/P4-16-spec.mdk
=> Clarified that slices apply to arbitrary-precision values

p4-16/spec/P4-16-spec.mdk
This pull request fixes a typo where upper-case `X` has been used instead of lower-case `x` in alternative example of illegal arithmetic expression.
=> p4-16-spec: fix typo

p4-16/spec/P4-16-spec.mdk
=> Clarified implicit casts in select expressions

p4-16/spec/P4-16-spec.mdk
This pull request clarifies that table entries cannot be specified for a table with no `key` property (or when the value of its `key` is empty list).
=> Clarify semantics for table entries without key

p4-16/spec/P4-16-spec.mdk
Since more people will more likely know about C++11 attributes than C# or Java, make reference to that instead.
C23 adds the same kind of attributes as C++11 had added so reference C23 too.
C# and Java are less likely to be known to many developers.
Remove reference to C's `#pragma`s since C++11/C23 attributes are more similar and `#pragma` are less likely to be used now.
=> Reference C++11/C23 attributes rather than Java or C#

p4-16/spec/P4-16-spec.mdk
I happened to notice this while trying to build HTML and PDF of the latest spec.
=> Fix spelling of an incorrect cross-reference

p4-16/psa/PSA.mdk, p4-16/psa/psa.p4
Rationale for this was added in change log section.
=> Fix #940 - Remove control plane API function signatures from PSA spec

p4-16/spec/P4-16-spec.mdk
=> Specify that comparison is legal for tuples

p4-16/spec/P4-16-spec.mdk
Even though the spec says table properties is
implemented as key-value pair, it could have been
the case where the last pair would have won.
This makes it explict that the if there is a
duplicated property, then the compiler should
reject it.
Fixes #1162
=> Add a note about duplicated table properties

p4-16/spec/P4-16-spec.mdk
There is no definition for a Begin/End block named "P4".
=> Small fix to incorrect Madoko markup

p4-16/psa/PSA.mdk, p4-16/psa/psa.p4
and explicitly say that it is on a best effort basis.
=> Attempt at clearer wording describing idle timeout notification in PSA

p4-16/spec/P4-16-spec.mdk
Fixes #1138 
This has been supported by the compiler for at least 5 years.
=> Specify key names generated for keys with masks

p4-16/spec/P4-16-spec.mdk
This PR clarifies the use of `bit<W>`, `int<W>`, and `varbit<W>`. More specifically, it states that these represent the case where the width of the type is either a constant integer or a compile-time known expression that evaluates to an integer. In other words, it addresses issue #1228.
=> Clarify fixed length types

p4-16/spec/P4-16-spec.mdk
This PR adds header unions as a subtype of header stacks and adds a new column in the type nesting section for header stacks, i.e., it addresses issues #876 and #1105
=> Fix header stack

p4-16/spec/P4-16-spec.mdk
This should be non-controversial as it documents what is
already the behavior of implementations of today.
Adding this sentence just clarifies the section
and if it is ok for an implementation not to implement
an infinite key size or a combination of match_kinds.
=> Add sentence about table's keys and implementation limitations

p4-16/spec/P4-16-spec.mdk
This small changes add information for `extract` operator then current header is a part of header union stack like in example from [this PR](https://github.com/p4lang/p4c/pull/3193).
For example:
```
header O1 {
bit<8> data;
}
header O2 {
bit<16> data;
}
header_union U {
O1 byte;
O2 short;
}
struct headers {
S    base;
U[2] u;
}
....
parser ParserImpl(packet_in packet, out headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
state start {
packet.extract(hdr.u.next.byte);
```
=> Add header union information for extract operator

p4-16/spec/P4-16-spec.mdk
=> Add compile-time size determination as an operation to types that support it

p4-16/spec/P4-16-spec.mdk
- Replaced `[#sec-determin]` with `(Section [#sec-determin])` globally
- Also, `sec-determin` doesn't exist. I think it should have been `sec-minsizeinbits`?
=> Fix and prettify references to compile-time size determination

p4-16/spec/P4-16-spec.mdk
=> Introduce invalid header union expressions

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
Summary of comments with approve/disapprove/change-requests as of 2022-Dec-27:
+ Sander Tolsma approved on 2022-Nov-16 after several of his review comments were addressed.
+ Mario Baldi approved in 2022-Nov
+ Steve Licking  approved in 2022-Nov
+ Mihai Budiu wrote several comments and created partial implementation in p4c.  Not clear whether he approves yet.
+ Andrew Pinski wrote some comments.  Overall approves of the idea, but would prefer a different syntax for specifying priorities of entries.
@thantry Please do provide your review comments, or approval of this PR as written.
=> Add definition of initial table entries, without const qualifier

p4-16/spec/P4-16-spec.mdk, p4-16/spec/grammar.mdk
This pull request addresses the issue #1273.
Added the definition allowing parentheses around lvalues to the grammar, similar to what was done in p4lang/p4c#4530.
In addition to that performed a minor cleanup, replacing the (copied) grammar code with the proper INCLUDE.
=> Allow parentheses in lvalues

p4-16/spec/P4-16-spec.mdk
I propose adding some clarifications to the spec, discussing how directionless, extern objects are passed to a control/parser. (#1276)
In the below parser type declaration, the first parameter, `packet_in b` is an directionless extern object.
```p4
parser Top(packet_in b, out Parsed_headers headers) {
```
Spec section **6.8. Calling convention: call by copy in/copy out** discusses the calling convention on directionless parameter as follows:
> The meaning of parameters with no direction depends upon the kind of entity the parameter is for:
> For anything other than an action, e.g. a control, parser, or function, a directionless parameter means that the value supplied as an argument in a call must be a compile-time known value (see Section …
=> Add explanation on passing directionless, extern object argument

p4-16/spec/P4-16-spec.mdk
This PR implements some good, but late-breaking suggestions on PR #1213 made by @ChrisDodd.
As a driveby: change a few occurrences of `bit<N>` and `int<N>` to `bit<W>` and `int<W>` respectively, for consistency with the rest of the specification.
=> Clarifications suggested by Chris Dodd

p4-16/spec/P4-16-spec.mdk
Otherwise it does not format it as a bulleted list.
=> Madoko requires blank line before first element of a list

p4-16/spec/P4-16-spec.mdk
This tries to resolve #1285. If merged in the current form, it would also fix #1293 and supercede PR #1294. I tried to make the "categories"/"kinds" of types (like headers and enums) distinct from actual types -- I used for each the name that is used in its section. Furthermore, in the second table (`typedef`/`type` rules) I've added the two missing lines for `string` and for list types. Apparently compiler handles them as would be expected / as I added.
I've also tried to add rationale for the `typedef` rules. I must say I am not happy with it and I wonder if someone can get a better one. Or we may just allow it (C allows typedefing even `void`).
Fixes #1285.
=> Clarify nesting rules

p4-16/spec/P4-16-spec.mdk
Discovered while comparing Madoko and AsciiDoc output.  In two out of three of the places changed by this PR, the text already wraps, or "escapes" its background-shaded box, in Madoko output.  The 3rd one is just quite long, and wraps in AsciiDoc but not Madoko, but seems worth shortening in any case.
=> Shorten long lines in code snippets v1

p4-16/spec/P4-16-spec.mdk
Fixes unmatched backticks (`) :)
=> Minor typo fix in section 8.11.2 Implicit casts

p4-16/spec/P4-16-spec.mdk
Following the discussion #1305, this PR clarifies that identifiers declared as constants with the `const` keyword is local compile-time known instead of compile-time known.
Also, I made a corresponding change in the constant declaration section (11.1) that the initializer for a constant should be local compile-time known.
=> Identifiers declared as constants are local compile-time known

.github/workflows/any-branch-uploads.yml, p4-16/spec/install-asciidoctor-linux.sh
- install rogue from upstream gem instead of building from source
- disable any-branch uploads job for now (possibly redundant with
asciidoc-build job)
=> Fix CI issues

p4-16/psa/PSA.adoc, p4-16/spec/P4-16-spec.adoc
This PR fixes the issue of [images not showing up](https://p4.org/p4-spec/docs/p4-16-working-draft.html) in specs built from Asciidocs in CI. The solution is to use the `:data-uri:` directive to embed images as data in the HTML.
=> embed images in html docs

p4-16/spec/P4-16-spec.adoc
This adds to the list of (local) compile-time known values in section 18.1. (#1323)
In summary, for index access,
* `e1[e2]` is local compile-time known if both `e1` and `e2` are local compile-time known.
* `e1[e2]` is compile-time known if both `e1` and `e2` are compile-time known.
* Note that `e1` should be of a header stack or tuple type.
And for field access,
* `e.x` is local compile-time known if `e` is local compile-time known.
* `e.x` is compile-time known if `e` is compile-time known.
* Note that `e` should be of a struct, header, or header union type.
=> Specify compile-time evaluation of field and index accesses

p4-16/spec/P4-16-spec.adoc
Following the discussion #1347, this specifies that the `size` argument of a `value_set` must be a compile-time known value.
Although the spec already implies it by mentioning:
> Parser Value Sets support a size argument to provide hints to the compiler to reserve hardware resources to implement the value set.
This revision makes it more explicit.
=> Specify that value_set's size is compile-time known

p4-16/spec/P4-16-spec.adoc
Closes #1292 and closes https://github.com/p4lang/p4c/issues/4792.
As mentioned in https://github.com/p4lang/p4c/issues/4792, `p4c` does not support the `priority` keyword for entries of a table that has `const entries`.
Feel free to suggest better wording or a better place for this addition.
=> [#1292] Explicitly state that table entries declared with 'const entries' cannot be assigned numeric priorities

p4-16/spec/P4-16-spec.adoc, p4-16/spec/grammar.adoc, p4-16/spec/scripts/README.md
This PR intentionally has 2 commits, in hopes of making it slightly easier to review.
The first commit _only_ reorders some definitions of nonterminal symbols in the grammar, without changing their contents at all in any other way, to make the order the same as the p4c implementation grammar, for easier diff'ing.  OK, that plus fixing one typo in a nonterminal name, and updating an example command in scripts/README.md for running that can help with easier diff'ing of the spec grammar vs. the p4c implementation grammar.
The second commit _only_ updates the definitions of nonterminals related to the new `for` loops, to make them closer to the p4c implementation grammar.  Those are the ones that require closer scrutiny on review, I think.
=> Update grammar to be closer to p4c implementation 2025 feb

p4-16/spec/P4-16-spec.adoc, p4-16/spec/grammar.adoc
The language specification added this rule in July 2019, but it was never added to the file grammar.adoc (formerly grammar.mdk), which appears to simply have been an oversight.
=> Update grammar.adoc to include abstract method declarations

.github/workflows/asciidoc-build.yml
Make it so that CI is run for pull requests. This is helpful when reviewing request and for PR submitters to see the CI rendering of spec changes.
=> enable CI build workflow on PRs

p4-16/spec/P4-16-spec.adoc
Following the discussion in #1349, this proposes some relaxation to **Appendix F: Restrictions on compile time and run time calls**.
**First, for runtime calls**,
(Current)
(Proposed) (EDITED)
(1) It adds a new column *top level* and refines the column *parser or control top level* (it is written *parser or top level* in the image, but it is likely a typo introduced while migrating to asciidoc) to *top level within a parser or control*.
(2) The explainer for the table has been modified such that the row *extern* means: both an extern method and a function, while it previously meant only the former. Also, the row *function* means: functions but not extern functions. (EDITED) 
(3) It *allows* function calls at the *top level within a parser or control*, but *disallows* function calls at the …
=> Relax runtime and compile-time callsite restrictions

p4-16/spec/P4-16-spec.adoc
Following #1346, this PR adds more rules to the semantics of abstract method initialization.
**First**, it *restricts* that the abstract method being implemented, must have the same parameter names as declared in the object declaration.
This is to (i) disambiguate what abstract method is being implemented, and (ii) provide a clear interface for users.
For example, one may define an extern object with overloaded abstract methods, as follows.
```p4
extern Virtual {
Virtual();
abstract bit<32> g(inout bit<32> x); // (1)
abstract bit<32> g(inout bit<32> y); // (2)
}
```
And in the instantiation site,
```p4
Virtual() virt = {
bit<32> g(inout bit<32> z) { return x - 1; } // (a)
bit<32> g(inout bit<32> w) { return x + 1; } // (b)
};
```
*Without* a restriction on matching parameter names, it is …
=> Clarify instantiation of objects with abstract methods

p4-16/spec/P4-16-spec.adoc
Following the discussion https://github.com/p4lang/p4-spec/issues/1295, this changes the code example of sec-type-variable-operations such that declaration of a local of a variable type happens inside a generic function, not a generic control.
=> Change code example for sec-type-variable-operations
